services:
  postgres:
    image: postgres:17.6-alpine
    container_name: walletly-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: walletlydb
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d walletlydb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - walletly-network

  backend:
    build:
      context: ../walletly-backend
      dockerfile: Dockerfile
    container_name: walletly-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/walletlydb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - walletly-network

  frontend:
    build:
      context: ../walletly-frontend
      dockerfile: Dockerfile
    container_name: walletly-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - walletly-network

volumes:
  postgres_data:

networks:
  walletly-network:
    driver: bridge